name: Expressions & Contexts
on: 
 workflow_dispatch:
  inputs:
   uername:
    description: "Enter your name"
    required: true
    default: "Prince"
run-name: "Expressions & Contexts by @${{ github.actor }}, event: ${{ github.event_name }}"
jobs:
  Saying-My-Name:
    runs-on: ubuntu-latest
    steps:
      - name: Say Name
        run: echo "My Name is ${{ inputs.username }}"
  Other-Steps:
    runs-on: ubuntu-latest
    steps:
      - name: Expressions
        run: |
          echo ${{ 1 }}
          echo ${{ 'This is a string' }}
          echo ${{ null }}
          echo ${{ true }}
          echo ${{ 1 > 2 }}
          echo ${{ 'string' == 'String' }}
          echo ${{ true && false }}
          echo ${{ true || (false && true) }}
      - name: Dump Contexts
        run: |
          echo '${{ toJson(github) }}'
          echo '${{ toJson(job) }}'
          echo '${{ toJson(secrets) }}'
          echo '${{ toJson(steps) }}'
          echo '${{ toJson(runner) }}'
      
      
